language: node
dist: xenial
install: npm install remark-cli remark-lint
script:
  - find -name '*.md' | grep -v 'node_modules' | xargs -n 1 -I '{}' node ./node_modules/remark-cli/cli.js {} -u remark-lint --frail
